### ISSUE TITLE
Illegal Division at zero

### ISSUE THREAD

**Issue by Red557** [tls-check/TLS-Check#7]
.. While running csv-result-to-summary.pl we get "Illegal division by zero at /usr/local/bin/csv-result-to-summary.pl line 242" for several domains. Any ieas what the problem could be here?

**Comment by opsec** [comment]
Can you tell us an example domain so that we can debug this ?

**Comment by opsec** [comment]
Ignore my question, it has nothing to do with the domain.

**Comment by opsec** [comment]
The initial requirement was to run the stats for several categories, and if no categories are given, the code has some spots where it does not handle this. Needs a fix.

**Comment by alvar-freude** [comment]
Hi,

> Am 11.04.2016 um 10:46 schrieb Red557 notifications@github.com:
> 
> .. While running csv-result-to-summary.pl we get "Illegal division by zero at /usr/local/bin/csv-result-to-summary.pl line 242" for several domains. Any ieas what the problem could be here?

thank you for the report, bug is fixed in the latest version from master (#8). This happened, when e.g. all domains in the input CSV didn’t support HTTPS and similar.

BTW:
The output of summarize is in german; maybe this should be i18n — I added this to the TODO.txt … ;-)

Ciao
  Alvar

## 

Alvar C.H. Freude
http://alvar.a-blast.org/ | http://blog.alvar-freude.de/

**Comment by alvar-freude** [comment]
I closed the issue, because fixed in #8 – please check and report when it still throws an error …
